# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gallery.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'gallery.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rgallery.proto\x12\x07gallery\"\x07\n\x05\x45mpty\"4\n\x0cIndexRequest\x12$\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x13.gallery.ImageEntry\"&\n\nImageEntry\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0c\n\x04path\x18\x02 \x01(\t\"1\n\rIndexResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"-\n\rSearchRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12\r\n\x05limit\x18\x02 \x01(\x05\"-\n\x0eSearchResponse\x12\x0b\n\x03ids\x18\x01 \x03(\x03\x12\x0e\n\x06scores\x18\x02 \x03(\x02\"\x1c\n\rDeleteRequest\x12\x0b\n\x03ids\x18\x01 \x03(\x03\"!\n\x0e\x44\x65leteResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"!\n\x0eHealthResponse\x12\x0f\n\x07healthy\x18\x01 \x01(\x08\x32\x82\x02\n\x0eGalleryService\x12<\n\x0bIndexImages\x12\x15.gallery.IndexRequest\x1a\x16.gallery.IndexResponse\x12\x39\n\x06Search\x12\x16.gallery.SearchRequest\x1a\x17.gallery.SearchResponse\x12?\n\x0c\x44\x65leteImages\x12\x16.gallery.DeleteRequest\x1a\x17.gallery.DeleteResponse\x12\x36\n\x0bHealthCheck\x12\x0e.gallery.Empty\x1a\x17.gallery.HealthResponseB&Z$github.com/gallery/internal/proto/pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gallery_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z$github.com/gallery/internal/proto/pb'
  _globals['_EMPTY']._serialized_start=26
  _globals['_EMPTY']._serialized_end=33
  _globals['_INDEXREQUEST']._serialized_start=35
  _globals['_INDEXREQUEST']._serialized_end=87
  _globals['_IMAGEENTRY']._serialized_start=89
  _globals['_IMAGEENTRY']._serialized_end=127
  _globals['_INDEXRESPONSE']._serialized_start=129
  _globals['_INDEXRESPONSE']._serialized_end=178
  _globals['_SEARCHREQUEST']._serialized_start=180
  _globals['_SEARCHREQUEST']._serialized_end=225
  _globals['_SEARCHRESPONSE']._serialized_start=227
  _globals['_SEARCHRESPONSE']._serialized_end=272
  _globals['_DELETEREQUEST']._serialized_start=274
  _globals['_DELETEREQUEST']._serialized_end=302
  _globals['_DELETERESPONSE']._serialized_start=304
  _globals['_DELETERESPONSE']._serialized_end=337
  _globals['_HEALTHRESPONSE']._serialized_start=339
  _globals['_HEALTHRESPONSE']._serialized_end=372
  _globals['_GALLERYSERVICE']._serialized_start=375
  _globals['_GALLERYSERVICE']._serialized_end=633
# @@protoc_insertion_point(module_scope)
