# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import gallery_pb2 as gallery__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in gallery_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GalleryServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.IndexImages = channel.unary_unary(
                '/gallery.GalleryService/IndexImages',
                request_serializer=gallery__pb2.IndexRequest.SerializeToString,
                response_deserializer=gallery__pb2.IndexResponse.FromString,
                _registered_method=True)
        self.Search = channel.unary_unary(
                '/gallery.GalleryService/Search',
                request_serializer=gallery__pb2.SearchRequest.SerializeToString,
                response_deserializer=gallery__pb2.SearchResponse.FromString,
                _registered_method=True)
        self.DeleteImages = channel.unary_unary(
                '/gallery.GalleryService/DeleteImages',
                request_serializer=gallery__pb2.DeleteRequest.SerializeToString,
                response_deserializer=gallery__pb2.DeleteResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/gallery.GalleryService/HealthCheck',
                request_serializer=gallery__pb2.Empty.SerializeToString,
                response_deserializer=gallery__pb2.HealthResponse.FromString,
                _registered_method=True)


class GalleryServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def IndexImages(self, request, context):
        """Index a list of images
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Search(self, request, context):
        """Search for images using a text query
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteImages(self, request, context):
        """Delete images from the index
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health check
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GalleryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'IndexImages': grpc.unary_unary_rpc_method_handler(
                    servicer.IndexImages,
                    request_deserializer=gallery__pb2.IndexRequest.FromString,
                    response_serializer=gallery__pb2.IndexResponse.SerializeToString,
            ),
            'Search': grpc.unary_unary_rpc_method_handler(
                    servicer.Search,
                    request_deserializer=gallery__pb2.SearchRequest.FromString,
                    response_serializer=gallery__pb2.SearchResponse.SerializeToString,
            ),
            'DeleteImages': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteImages,
                    request_deserializer=gallery__pb2.DeleteRequest.FromString,
                    response_serializer=gallery__pb2.DeleteResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=gallery__pb2.Empty.FromString,
                    response_serializer=gallery__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'gallery.GalleryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('gallery.GalleryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GalleryService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def IndexImages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gallery.GalleryService/IndexImages',
            gallery__pb2.IndexRequest.SerializeToString,
            gallery__pb2.IndexResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Search(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gallery.GalleryService/Search',
            gallery__pb2.SearchRequest.SerializeToString,
            gallery__pb2.SearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteImages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gallery.GalleryService/DeleteImages',
            gallery__pb2.DeleteRequest.SerializeToString,
            gallery__pb2.DeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gallery.GalleryService/HealthCheck',
            gallery__pb2.Empty.SerializeToString,
            gallery__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
