// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v6.31.1
// source: gallery.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GalleryService_IndexImages_FullMethodName  = "/gallery.GalleryService/IndexImages"
	GalleryService_Search_FullMethodName       = "/gallery.GalleryService/Search"
	GalleryService_DeleteImages_FullMethodName = "/gallery.GalleryService/DeleteImages"
	GalleryService_HealthCheck_FullMethodName  = "/gallery.GalleryService/HealthCheck"
)

// GalleryServiceClient is the client API for GalleryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GalleryServiceClient interface {
	// Index a list of images
	IndexImages(ctx context.Context, in *IndexRequest, opts ...grpc.CallOption) (*IndexResponse, error)
	// Search for images using a text query
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
	// Delete images from the index
	DeleteImages(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	// Health check
	HealthCheck(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HealthResponse, error)
}

type galleryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGalleryServiceClient(cc grpc.ClientConnInterface) GalleryServiceClient {
	return &galleryServiceClient{cc}
}

func (c *galleryServiceClient) IndexImages(ctx context.Context, in *IndexRequest, opts ...grpc.CallOption) (*IndexResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IndexResponse)
	err := c.cc.Invoke(ctx, GalleryService_IndexImages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *galleryServiceClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, GalleryService_Search_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *galleryServiceClient) DeleteImages(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, GalleryService_DeleteImages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *galleryServiceClient) HealthCheck(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, GalleryService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GalleryServiceServer is the server API for GalleryService service.
// All implementations must embed UnimplementedGalleryServiceServer
// for forward compatibility.
type GalleryServiceServer interface {
	// Index a list of images
	IndexImages(context.Context, *IndexRequest) (*IndexResponse, error)
	// Search for images using a text query
	Search(context.Context, *SearchRequest) (*SearchResponse, error)
	// Delete images from the index
	DeleteImages(context.Context, *DeleteRequest) (*DeleteResponse, error)
	// Health check
	HealthCheck(context.Context, *Empty) (*HealthResponse, error)
	mustEmbedUnimplementedGalleryServiceServer()
}

// UnimplementedGalleryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGalleryServiceServer struct{}

func (UnimplementedGalleryServiceServer) IndexImages(context.Context, *IndexRequest) (*IndexResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IndexImages not implemented")
}
func (UnimplementedGalleryServiceServer) Search(context.Context, *SearchRequest) (*SearchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Search not implemented")
}
func (UnimplementedGalleryServiceServer) DeleteImages(context.Context, *DeleteRequest) (*DeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteImages not implemented")
}
func (UnimplementedGalleryServiceServer) HealthCheck(context.Context, *Empty) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedGalleryServiceServer) mustEmbedUnimplementedGalleryServiceServer() {}
func (UnimplementedGalleryServiceServer) testEmbeddedByValue()                        {}

// UnsafeGalleryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GalleryServiceServer will
// result in compilation errors.
type UnsafeGalleryServiceServer interface {
	mustEmbedUnimplementedGalleryServiceServer()
}

func RegisterGalleryServiceServer(s grpc.ServiceRegistrar, srv GalleryServiceServer) {
	// If the following call panics, it indicates UnimplementedGalleryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GalleryService_ServiceDesc, srv)
}

func _GalleryService_IndexImages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IndexRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GalleryServiceServer).IndexImages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GalleryService_IndexImages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GalleryServiceServer).IndexImages(ctx, req.(*IndexRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GalleryService_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GalleryServiceServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GalleryService_Search_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GalleryServiceServer).Search(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GalleryService_DeleteImages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GalleryServiceServer).DeleteImages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GalleryService_DeleteImages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GalleryServiceServer).DeleteImages(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GalleryService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GalleryServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GalleryService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GalleryServiceServer).HealthCheck(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// GalleryService_ServiceDesc is the grpc.ServiceDesc for GalleryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GalleryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gallery.GalleryService",
	HandlerType: (*GalleryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IndexImages",
			Handler:    _GalleryService_IndexImages_Handler,
		},
		{
			MethodName: "Search",
			Handler:    _GalleryService_Search_Handler,
		},
		{
			MethodName: "DeleteImages",
			Handler:    _GalleryService_DeleteImages_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _GalleryService_HealthCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gallery.proto",
}
