// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddFolder(arg1) {
  return window['go']['main']['App']['AddFolder'](arg1);
}

export function ClearAllData() {
  return window['go']['main']['App']['ClearAllData']();
}

export function GetImages(arg1) {
  return window['go']['main']['App']['GetImages'](arg1);
}

export function GetWatchedFolders() {
  return window['go']['main']['App']['GetWatchedFolders']();
}

export function OpenImage(arg1) {
  return window['go']['main']['App']['OpenImage'](arg1);
}

export function Reindex() {
  return window['go']['main']['App']['Reindex']();
}

export function RemoveFolder(arg1) {
  return window['go']['main']['App']['RemoveFolder'](arg1);
}

export function Search(arg1, arg2) {
  return window['go']['main']['App']['Search'](arg1, arg2);
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}
