// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddFolder(arg1:string):Promise<string>;

export function ClearAllData():Promise<string>;

export function GetImages(arg1:number):Promise<Array<main.ImageResult>>;

export function GetWatchedFolders():Promise<Array<string>>;

export function OpenImage(arg1:string):Promise<void>;

export function Reindex():Promise<void>;

export function RemoveFolder(arg1:string):Promise<string>;

export function Search(arg1:string,arg2:number):Promise<Array<main.ImageResult>>;

export function SelectFolder():Promise<string>;
